import { StyleSheet } from "react-native";

const colors = {
  bg: "#F8F6FD",
  surface: "#FFFFFF",
  purple: "#572EA9",
  purple2: "#764EC7",
  lilac: "#A47CF3",
  light: "#B189FF",
  pink: "#DBB5EE",
  pale: "#EDE5FD",
  text: "#2E2250",
  muted: "#7C7193",
  border: "#E7DFF5",
  soft: "#F3EEFC",
};

const shadow = {
  shadowColor: "#572EA9",
  shadowOpacity: 0.10,
  shadowRadius: 16,
  shadowOffset: { width: 0, height: 7 },
  elevation: 4,
};

const styles = StyleSheet.create({
  // LOGIN
  container: {
    flex: 1,
    backgroundColor: colors.bg,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  topCircle: {
    position: "absolute",
    top: -180,
    left: -100,
    width: 520,
    height: 380,
    borderRadius: 260,
    backgroundColor: colors.light,
    opacity: 0.24,
  },
  menu: { position: "absolute", top: 48, right: 24, padding: 10 },
  logoInicio: {
    fontSize: 52,
    fontWeight: "900",
    letterSpacing: 3,
    color: colors.purple,
    marginBottom: 12,
  },
  loginButton: {
    width: "100%",
    maxWidth: 320,
    height: 56,
    borderRadius: 18,
    backgroundColor: colors.purple,
    justifyContent: "center",
    alignItems: "center",
    ...shadow,
  },
  loginText: { color: "#fff", fontSize: 16, fontWeight: "800" },
  bottomCircle: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: 86,
    backgroundColor: colors.purple2,
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  connectionText: { color: "#fff", fontWeight: "800", letterSpacing: 1 },

  // ESTRUTURA MOBILE
  appShell: { flex: 1, backgroundColor: colors.bg },
  mobileHeader: {
    minHeight: 214,
    backgroundColor: colors.purple,
    paddingTop: 46,
    paddingHorizontal: 20,
    paddingBottom: 24,
    overflow: "hidden",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  headerBubbleOne: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: colors.light,
    opacity: 0.16,
    right: -80,
    top: -75,
  },
  headerBubbleTwo: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: colors.pink,
    opacity: 0.10,
    left: -60,
    bottom: -90,
  },
  headerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brandRow: { flexDirection: "row", alignItems: "center" },
  mobileBrandIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.16)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.20)",
  },
  mobileBrandName: {
    fontSize: 21,
    fontWeight: "900",
    color: "#FFFFFF",
    letterSpacing: 1,
  },
  mobileBrandCaption: {
    fontSize: 10,
    color: "#EDE5FD",
    marginTop: 1,
  },
  mobileNotification: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  mobileNotificationBadge: {
    position: "absolute",
    right: -3,
    top: -3,
    width: 17,
    height: 17,
    borderRadius: 9,
    backgroundColor: colors.lilac,
    borderWidth: 2,
    borderColor: colors.purple,
    justifyContent: "center",
    alignItems: "center",
  },
  mobileNotificationBadgeText: { color: "#FFFFFF", fontSize: 8, fontWeight: "900" },
  mobilePageInfo: { marginTop: 26, paddingRight: 12 },
  mobileEyebrow: {
    color: colors.pink,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.5,
  },
  mobilePageTitle: { color: "#FFFFFF", fontSize: 28, fontWeight: "900", marginTop: 5 },
  mobilePageSubtitle: {
    color: "#EDE5FD",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
  },
  pageScroll: { flex: 1 },
  pageContent: { padding: 18, paddingBottom: 110 },
  pageFooter: { alignItems: "center", marginTop: 24, marginBottom: 8 },
  secureRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  footerSecure: { fontSize: 10, color: colors.muted },
  copyright: { fontSize: 9, color: "#A397B7", marginTop: 8 },

  // NAVEGAÇÃO INFERIOR
  bottomNavigation: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
    height: 70,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 5,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow,
  },
  bottomTab: { flex: 1, alignItems: "center", justifyContent: "center" },
  bottomTabIcon: {
    width: 36,
    height: 32,
    borderRadius: 11,
    justifyContent: "center",
    alignItems: "center",
  },
  bottomTabIconActive: { backgroundColor: colors.purple2 },
  bottomTabText: { color: "#8B7FA3", fontSize: 9, fontWeight: "700", marginTop: 3 },
  bottomTabTextActive: { color: colors.purple, fontWeight: "900" },

  // CONTEÚDO
  contentCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    padding: 17,
    marginBottom: 14,
    ...shadow,
  },
  sectionHeading: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  sectionIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: colors.soft,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 11,
  },
  sectionTitle: { fontSize: 16, color: colors.text, fontWeight: "900" },
  sectionDescription: { fontSize: 10, color: colors.muted, marginTop: 3 },
  formGrid: { width: "100%" },
  formField: { width: "100%", marginBottom: 13 },
  label: { fontSize: 11, color: colors.text, fontWeight: "800", marginBottom: 7 },
  input: {
    height: 50,
    backgroundColor: "#FCFBFE",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    fontSize: 13,
    color: colors.text,
  },
  pickerContainer: {
    height: 50,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#FCFBFE",
  },
  picker: { height: 50, color: colors.text, fontSize: 13 },
  inputIcon: {
    height: 50,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FCFBFE",
  },
  dateText: { flex: 1, fontSize: 13, color: colors.muted },
  row: { flexDirection: "row", alignItems: "center" },
  obsInput: {
    height: 50,
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    fontSize: 13,
    color: colors.text,
    backgroundColor: "#FCFBFE",
  },
  addButton: {
    width: 50,
    height: 50,
    borderRadius: 14,
    backgroundColor: colors.purple,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  saveButton: {
    marginTop: 5,
    width: "100%",
    height: 52,
    borderRadius: 16,
    backgroundColor: colors.purple,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    ...shadow,
  },
  saveText: { fontSize: 13, color: "#fff", fontWeight: "900", marginLeft: 8 },

  // MEDICAÇÕES
  cardsGrid: { width: "100%" },
  cardShadow: { width: "100%", marginBottom: 14 },
  medicCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 17,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow,
  },
  cardTop: { flexDirection: "row", alignItems: "center" },
  remedioIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: colors.soft,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 11,
  },
  remedioEmoji: { fontSize: 24 },
  nomeMedicamento: { fontSize: 16, color: colors.text, fontWeight: "900" },
  doseMedicamento: { fontSize: 11, color: colors.muted, marginTop: 3 },
  smallIconButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: colors.soft,
    justifyContent: "center",
    alignItems: "center",
  },
  horariosRow: { flexDirection: "row", marginTop: 16 },
  horarioBox: {
    backgroundColor: colors.pale,
    borderRadius: 12,
    paddingVertical: 9,
    paddingHorizontal: 11,
    flexDirection: "row",
    alignItems: "center",
    marginRight: 8,
  },
  horarioText: { fontSize: 11, color: colors.purple, fontWeight: "900", marginLeft: 6 },
  cardBottom: {
    marginTop: 16,
    paddingTop: 13,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  medicoText: { fontSize: 10, color: colors.muted },

  // ANÁLISES
  cardAnalise: {
    width: "100%",
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 17,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
    ...shadow,
  },
  cardTitulo: { fontSize: 15, color: colors.text, fontWeight: "900" },
  cardSub: { fontSize: 10, color: colors.muted, marginTop: 4 },
  graficoArea: { height: 135, flexDirection: "row", alignItems: "flex-end", paddingTop: 16 },
  barra: { flex: 1, borderRadius: 7, backgroundColor: colors.purple2, marginHorizontal: 3 },
  pizzaFake: {
    width: 122,
    height: 122,
    borderRadius: 61,
    backgroundColor: colors.light,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 14,
    borderWidth: 16,
    borderColor: colors.purple2,
  },
  pizzaInterna: { width: 56, height: 56, borderRadius: 28, backgroundColor: "#fff" },
  graficoHorario: { height: 135, flexDirection: "row", alignItems: "flex-end", paddingTop: 16 },
  barraAzul: { flex: 1, borderRadius: 7, backgroundColor: colors.lilac, marginHorizontal: 3 },

  // CINTA
  cintaCard: {
    width: "100%",
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
    ...shadow,
  },
  cintaCardTop: { flexDirection: "row", alignItems: "center" },
  bluetoothCircle: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: colors.soft,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  dispositivoTitulo: { fontSize: 16, color: colors.text, fontWeight: "900" },
  desconectado: { fontSize: 11, color: colors.purple2, marginTop: 4, fontWeight: "800" },
  conectarButton: {
    height: 52,
    borderRadius: 16,
    backgroundColor: colors.purple,
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    ...shadow,
  },
  conectarText: { fontSize: 13, color: "#fff", fontWeight: "900", marginLeft: 8 },
  infoCard: {
    width: "100%",
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow,
  },
  passoRow: { flexDirection: "row", alignItems: "center", marginTop: 14 },
  numeroCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.purple,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  numeroText: { fontSize: 11, color: "#fff", fontWeight: "900" },
  passoTexto: { flex: 1, fontSize: 11, color: colors.muted, lineHeight: 16, marginRight: 8 },

  // DASHBOARD
  dashboardHero: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 22,
    padding: 20,
    ...shadow,
  },
  dashboardHeroText: { width: "100%" },
  dashboardEyebrow: { fontSize: 10, color: colors.purple2, fontWeight: "900", letterSpacing: 1.2 },
  dashboardHeroTitle: { fontSize: 24, color: colors.text, fontWeight: "900", marginTop: 8, lineHeight: 30 },
  dashboardHeroSub: { fontSize: 12, color: colors.muted, lineHeight: 18, marginTop: 10 },
  dashboardIcon: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: colors.soft,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-end",
    marginTop: 16,
  },
  statsRow: { width: "100%", marginTop: 14 },
  statCard: {
    width: "100%",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 17,
    marginBottom: 11,
    ...shadow,
  },
  statValue: { fontSize: 28, color: colors.purple, fontWeight: "900" },
  statLabel: { fontSize: 11, color: colors.muted, marginTop: 5, fontWeight: "700" },
});

export default styles;
